// apps/demo/src/pages/ProsemirrorDemo.tsx
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import * as Y from '@y/y';
import { Awareness } from '@y/protocols/awareness';
import {
  ProtocolProvider,
  ProviderStatus,
} from '@y-kafka-collabation-server/provider';
import { EditorState } from 'prosemirror-state';
import { EditorView } from 'prosemirror-view';
import { schema as basicSchema } from 'prosemirror-schema-basic';
import { history } from 'prosemirror-history';
import { keymap } from 'prosemirror-keymap';
import { baseKeymap } from 'prosemirror-commands';
import {
  ySyncPlugin,
  yCursorPlugin,
  yUndoPlugin,
  initProseMirrorDoc,
  undo,
  redo,
} from 'y-prosemirror';
import { fetchStatus, persistSnapshot, ServerStatus } from '../lib/api';

const VITE_COLLAB_SERVER_URL =
  import.meta.env.VITE_COLLAB_SERVER_URL ?? 'http://localhost:3000';

export const ProsemirrorDemo = () => {
  const [docId, setDocId] = useState('demo-doc');
  const [inputDocId, setInputDocId] = useState(docId);
  const editorRef = useRef<HTMLDivElement | null>(null);
  const editorViewRef = useRef<EditorView | null>(null);

  // Re-create Y.Doc when docId changes to ensure clean state
  const ydoc = useMemo(() => new Y.Doc({ guid: docId }), [docId]);
  const awareness = useMemo(() => new Awareness(ydoc), [ydoc]);

  const [serverStatus, setServerStatus] = useState<ServerStatus[]>([]);
  const [lastSync, setLastSync] = useState<string | null>(null);
  const [statusMessage, setStatusMessage] = useState('尚未发送');
  const [providerStatus, setProviderStatus] =
    useState<ProviderStatus>('disconnected');
  const [lastProviderSync, setLastProviderSync] = useState<string | null>(null);
  const [providerLog, setProviderLog] = useState<string[]>([]);

  const handlePersist = useCallback(async () => {
    const snapshot = JSON.stringify(ydoc.toJSON());
    setStatusMessage('正在持久化');
    await persistSnapshot(VITE_COLLAB_SERVER_URL, docId, snapshot);
    setLastSync(new Date().toISOString());
    setStatusMessage('快照已保存');
  }, [ydoc, docId]);

  const handleFetchStatus = useCallback(async () => {
    try {
      const status = await fetchStatus(VITE_COLLAB_SERVER_URL);
      setServerStatus(status);
    } catch (error) {
      console.error(error);
    }
  }, []);

  useEffect(() => {
    handleFetchStatus();
    const interval = setInterval(handleFetchStatus, 5000);
    return () => clearInterval(interval);
  }, [handleFetchStatus]);

  const yXmlFragment = useMemo(
    () => ydoc.getXmlFragment('prosemirror'),
    [ydoc],
  );

  useEffect(() => {
    if (!editorRef.current) return;

    editorRef.current.innerHTML = '';
    const { doc: initialDoc, mapping } = initProseMirrorDoc(
      yXmlFragment as any,
      basicSchema,
    );

    const state = EditorState.create({
      schema: basicSchema,
      doc: initialDoc,
      plugins: [
        ySyncPlugin(yXmlFragment as any, { mapping }),
        yCursorPlugin(awareness as any),
        yUndoPlugin(),
        history(),
        keymap({
          'Mod-z': undo,
          'Mod-y': redo,
          'Mod-Shift-z': redo,
        }),
        keymap(baseKeymap),
      ],
    });

    const view = new EditorView(editorRef.current, { state });
    editorViewRef.current = view;
    return () => {
      view.destroy();
      editorViewRef.current = null;
    };
  }, [awareness, yXmlFragment]);

  const pushProviderLog = useCallback((message: string) => {
    setProviderLog((prev) => {
      const next = [message, ...prev];
      return next.slice(0, 10);
    });
  }, []);

  useEffect(() => {
    // Reset logs on doc switch
    setProviderLog([]);
    setLastProviderSync(null);
    setProviderStatus('disconnected');

    const provider = new ProtocolProvider(ydoc, {
      url: VITE_COLLAB_SERVER_URL,
      docId: docId,
      roomId: 'collab-doc', // Use 'collab-doc' as the room type/namespace
      awareness,
      metadataCustomizer: (metadata) => ({
        ...metadata,
        version: Date.now().toString(),
      }),
    });

    provider.on('status', (value) => {
      setProviderStatus(value);
      pushProviderLog(`状态：${value} · ${new Date().toLocaleTimeString()}`);
    });
    provider.on('sync', () => {
      setLastProviderSync(new Date().toISOString());
      pushProviderLog(`SyncStep2 完成 · ${new Date().toLocaleTimeString()}`);
    });
    provider.on('awareness', (changes) => {
      const touched = [
        ...changes.added,
        ...changes.updated,
        ...changes.removed,
      ];
      pushProviderLog(
        `Awareness: ${touched.length ? touched.join(', ') : 'none'} · ${new Date().toLocaleTimeString()}`,
      );
    });

    return () => {
      provider.destroy();
    };
  }, [ydoc, docId, awareness, pushProviderLog]);

  const switchDoc = (e: React.FormEvent) => {
    e.preventDefault();
    if (inputDocId && inputDocId !== docId) {
      setDocId(inputDocId);
    }
  };

  return (
    <div className="demo-page">
      <header className="page-header">
        <h2>Prosemirror 协同编辑器</h2>
        <div className="doc-switcher">
          <form onSubmit={switchDoc}>
            <label>当前文档 ID: </label>
            <input
              value={inputDocId}
              onChange={(e) => setInputDocId(e.target.value)}
              placeholder="Enter Doc ID"
            />
            <button type="submit">切换文档</button>
          </form>
        </div>
      </header>

      <div className="content-grid">
        <article className="editor-panel">
          <div className="editor-toolbar">
            <button type="button" onClick={handlePersist}>
              保存 Snapshot
            </button>
            <span className="status-chip">{statusMessage}</span>
          </div>
          <div ref={editorRef} className="editor" />
          <p className="editor-footnote">
            当前连接到 Room: <strong>{docId}</strong>
          </p>
        </article>

        <aside className="status-panel">
          <div className="provider-card">
            <h3>ProtocolProvider 状态</h3>
            <p>
              连接状态：
              <span className={`status-${providerStatus}`}>
                {providerStatus}
              </span>
            </p>
            <p>
              上次同步：
              {lastProviderSync
                ? `${new Date(lastProviderSync).toLocaleTimeString()}`
                : '尚未完成'}
            </p>
            <div className="provider-log">
              {providerLog.map((entry, i) => (
                <div key={i} className="log-entry">
                  {entry}
                </div>
              ))}
            </div>
          </div>

          <div className="server-status-list">
            <h3>Server 活跃文档</h3>
            <ul>
              {serverStatus.map((entry) => (
                <li
                  key={entry.docId}
                  className={entry.docId === docId ? 'active' : ''}
                >
                  <strong>{entry.docId}</strong>
                  <div>Msgs: {entry.kafkaMessageCount}</div>
                  <div>Snap: {entry.latestSnapshot ? '✅' : '❌'}</div>
                </li>
              ))}
            </ul>
          </div>
        </aside>
      </div>
    </div>
  );
};

// apps/demo/src/pages/ProsemirrorDemo.vue
<template>
  <div class="demo-page">
    <header class="page-header">
      <h2>Prosemirror 协同编辑器</h2>
      <div class="doc-switcher">
        <form @submit.prevent="switchDoc">
          <label>当前文档 ID: </label>
          <input v-model="inputDocId" placeholder="Enter Doc ID" />
          <button type="submit">切换文档</button>
        </form>
      </div>
    </header>

    <div class="content-grid">
      <article class="editor-panel">
        <div class="editor-toolbar">
          <button type="button" @click="handlePersist">保存 Snapshot</button>
          <span class="status-chip">{{ statusMessage }}</span>
        </div>
        <div ref="editorRef" class="editor" />
        <p class="editor-footnote">
          当前连接到 Room: <strong>{{ docId }}</strong>
        </p>
      </article>

      <aside class="status-panel">
        <div class="provider-card">
          <h3>ProtocolProvider 状态</h3>
          <p>
            连接状态：
            <span :class="`status-${providerStatus}`">
              {{ providerStatus }}
            </span>
          </p>
          <p>
            上次同步：
            {{ lastProviderSync ? new Date(lastProviderSync).toLocaleTimeString() : '尚未完成' }}
          </p>
          <div class="provider-log">
            <div v-for="(entry, index) in providerLog" :key="index" class="log-entry">
              {{ entry }}
            </div>
          </div>
        </div>

        <div class="server-status-list">
          <h3>Server 活跃文档</h3>
          <ul>
            <li
              v-for="entry in serverStatus"
              :key="entry.docId"
              :class="{ active: entry.docId === docId }"
            >
              <strong>{{ entry.docId }}</strong>
              <div>Msgs: {{ entry.kafkaMessageCount }}</div>
              <div>Snap: {{ entry.latestSnapshot ? '✅' : '❌' }}</div>
            </li>
          </ul>
        </div>
      </aside>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, shallowRef, watch, watchEffect, onMounted, onBeforeUnmount } from 'vue';
import * as Y from '@y/y';
import { Awareness } from '@y/protocols/awareness';
import {
  ProtocolProvider,
  ProviderStatus,
} from '@y-kafka-collabation-server/provider';
import { EditorState } from 'prosemirror-state';
import { EditorView } from 'prosemirror-view';
import { schema as basicSchema } from 'prosemirror-schema-basic';
import { history } from 'prosemirror-history';
import { keymap } from 'prosemirror-keymap';
import { baseKeymap } from 'prosemirror-commands';
import {
  ySyncPlugin,
  yCursorPlugin,
  yUndoPlugin,
  initProseMirrorDoc,
  undo,
  redo,
} from 'y-prosemirror';
import { fetchStatus, persistSnapshot, ServerStatus } from '../lib/api';

const VITE_COLLAB_SERVER_URL =
  import.meta.env.VITE_COLLAB_SERVER_URL ?? 'http://localhost:3000';

const docId = ref('demo-doc');
const inputDocId = ref(docId.value);

const editorRef = ref<HTMLDivElement | null>(null);
const editorView = shallowRef<EditorView | null>(null);
const ydoc = shallowRef<Y.Doc>();
const awareness = shallowRef<Awareness>();
const provider = shallowRef<ProtocolProvider | null>(null);

const serverStatus = ref<ServerStatus[]>([]);
const statusMessage = ref('尚未发送');
const providerStatus = ref<ProviderStatus>('disconnected');
const lastProviderSync = ref<string | null>(null);
const providerLog = ref<string[]>([]);
let statusInterval: ReturnType<typeof setInterval> | null = null;

const recreateCollabState = (id: string) => {
  ydoc.value = new Y.Doc({ guid: id });
  awareness.value = new Awareness(ydoc.value);
};

recreateCollabState(docId.value);

watch(docId, (id) => {
  if (id) {
    recreateCollabState(id);
  }
});

const pushProviderLog = (message: string) => {
  providerLog.value = [message, ...providerLog.value].slice(0, 10);
};

const handlePersist = async () => {
  if (!ydoc.value) return;
  const snapshot = JSON.stringify(ydoc.value.toJSON());
  statusMessage.value = '正在持久化';
  await persistSnapshot(VITE_COLLAB_SERVER_URL, docId.value, snapshot);
  statusMessage.value = '快照已保存';
};

const handleFetchStatus = async () => {
  try {
    serverStatus.value = await fetchStatus(VITE_COLLAB_SERVER_URL);
  } catch (error) {
    console.error(error);
  }
};

onMounted(() => {
  handleFetchStatus();
  statusInterval = setInterval(handleFetchStatus, 5000);
});

watchEffect((onCleanup) => {
  const container = editorRef.value;
  const doc = ydoc.value;
  const aw = awareness.value;
  if (!container || !doc || !aw) {
    return;
  }

  container.innerHTML = '';
  const fragment = doc.getXmlFragment('prosemirror');
  const { doc: initialDoc, mapping } = initProseMirrorDoc(
    fragment as any,
    basicSchema,
  );

  const state = EditorState.create({
    schema: basicSchema,
    doc: initialDoc,
    plugins: [
      ySyncPlugin(fragment as any, { mapping }),
      yCursorPlugin(aw as any),
      yUndoPlugin(),
      history(),
      keymap({
        'Mod-z': undo,
        'Mod-y': redo,
        'Mod-Shift-z': redo,
      }),
      keymap(baseKeymap),
    ],
  });

  const view = new EditorView(container, { state });
  editorView.value = view;

  onCleanup(() => {
    view.destroy();
    if (editorView.value === view) {
      editorView.value = null;
    }
  });
});

watchEffect((onCleanup) => {
  const doc = ydoc.value;
  const aw = awareness.value;
  const currentDocId = docId.value;
  if (!doc || !aw) {
    return;
  }

  providerLog.value = [];
  lastProviderSync.value = null;
  providerStatus.value = 'disconnected';

  const instance = new ProtocolProvider(doc, {
    url: VITE_COLLAB_SERVER_URL,
    docId: currentDocId,
    roomId: 'collab-doc',
    awareness: aw,
    metadataCustomizer: (metadata) => ({
      ...metadata,
      version: Date.now().toString(),
    }),
  });

  instance.on('status', (value) => {
    providerStatus.value = value;
    pushProviderLog(`状态：${value} · ${new Date().toLocaleTimeString()}`);
  });
  instance.on('sync', () => {
    lastProviderSync.value = new Date().toISOString();
    pushProviderLog(`SyncStep2 完成 · ${new Date().toLocaleTimeString()}`);
  });
  instance.on('awareness', (changes) => {
    const touched = [
      ...changes.added,
      ...changes.updated,
      ...changes.removed,
    ];
    pushProviderLog(
      `Awareness: ${
        touched.length ? touched.join(', ') : 'none'
      } · ${new Date().toLocaleTimeString()}`,
    );
  });

  provider.value = instance;

  onCleanup(() => {
    instance.destroy();
    if (provider.value === instance) {
      provider.value = null;
    }
  });
});

const switchDoc = () => {
  if (inputDocId.value && inputDocId.value !== docId.value) {
    docId.value = inputDocId.value;
  }
};

onBeforeUnmount(() => {
  provider.value?.destroy();
  provider.value = null;
  editorView.value?.destroy();
  editorView.value = null;
  if (statusInterval) {
    clearInterval(statusInterval);
    statusInterval = null;
  }
});
</script>
